module.exports = {
	// HTTP
	HTTP_MULTIPLE_CHOICES: 'Multiple Choices',
	HTTP_MOVED_PERMANENTLY: 'Moved Permanently',
	HTTP_MOVED_TEMPORARILY: 'Moved Temporarily',
	HTTP_SEE_OTHER: 'See Other',
	HTTP_NOT_MODIFIED: 'Not Modified',
	HTTP_USE_PROXY: 'Use Proxy',
	HTTP_TEMPORARY_REDIRECT: 'Temporary Redirect',
	HTTP_PERMANENT_REDIRECT: 'Permanent Redirect',
	HTTP_BAD_REQUEST: 'Bad Request',
	HTTP_UNAUTHORIZED: 'Unauthorized',
	HTTP_PAYMENT_REQUIRED: 'Payment Required',
	HTTP_FORBIDDEN: 'Forbidden',
	HTTP_NOT_FOUND: 'Not Found',
	HTTP_METHOD_NOT_ALLOWED: 'Method Not Allowed',
	HTTP_NOT_ACCEPTABLE: 'Not Acceptable',
	HTTP_PROXY_AUTHENTICATION_REQUIRED: 'Proxy Authentication Required',
	HTTP_REQUEST_TIMEOUT: 'Request Timeout',
	HTTP_CONFLICT: 'Conflict',
	HTTP_GONE: 'Gone',
	HTTP_LENGTH_REQUIRED: 'Length Required',
	HTTP_PRECONDITION_FAILED: 'Precondition Failed',
	HTTP_REQUEST_TOO_LONG: 'Request Entity Too Large',
	HTTP_REQUEST_URI_TOO_LONG: 'Request-URI Too Long',
	HTTP_UNSUPPORTED_MEDIA_TYPE: 'Unsupported Media Type',
	HTTP_REQUESTED_RANGE_NOT_SATISFIABLE: 'Requested Range Not Satisfiable',
	HTTP_EXPECTATION_FAILED: 'Expectation Failed',
	HTTP_IM_A_TEAPOT: "I'm a teapot",
	HTTP_INSUFFICIENT_SPACE_ON_RESOURCE: 'Insufficient Space on Resource',
	HTTP_METHOD_FAILURE: 'Method Failure',
	HTTP_MISDIRECTED_REQUEST: 'Misdirected Request',
	HTTP_UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
	HTTP_LOCKED: 'Locked',
	HTTP_FAILED_DEPENDENCY: 'Failed Dependency',
	HTTP_PRECONDITION_REQUIRED: 'Precondition Required',
	HTTP_TOO_MANY_REQUESTS: 'Too Many Requests',
	HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: 'Request Header Fields Too Large',
	HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: 'Unavailable For Legal Reasons',
	HTTP_INTERNAL_SERVER_ERROR: 'Internal Server Error',
	HTTP_NOT_IMPLEMENTED: 'Not Implemented',
	HTTP_BAD_GATEWAY: 'Bad Gateway',
	HTTP_SERVICE_UNAVAILABLE: 'Service Unavailable',
	HTTP_GATEWAY_TIMEOUT: 'Gateway Timeout',
	HTTP_HTTP_VERSION_NOT_SUPPORTED: 'HTTP Version Not Supported',
	HTTP_INSUFFICIENT_STORAGE: 'Insufficient Storage',
	HTTP_NETWORK_AUTHENTICATION_REQUIRED: 'Network Authentication Required',

	// ffmpeg
	STREAM_NOT_FOUND: 'Stream not found',
	UNKNOWN: 'Unknown error occurred',
}
